// QR codes as inline SVG (browser only; library from jsDelivr, pinned).
import qrcode from 'https://cdn.jsdelivr.net/npm/qrcode-generator@2.0.4/+esm';

// Returns SVG markup generated by the library (not user data), so it is safe
// to insert with raw(): html`<div>${raw(qrSvg(url))}</div>`.
export function qrSvg(text) {
  const qr = qrcode(0, 'M');
  qr.addData(text);
  qr.make();
  return qr.createSvgTag({ cellSize: 4, margin: 2, scalable: true });
}
